const monList = [
  {
    id: 'tripole',
    name: 'Tripole',
    description: 'A shy tadpole Mon with three big eyes.',
    image: require('../assets/images/mons/tripole.png'),
    unlocked: false,
  },
  {
    id: 'trifin',
    name: 'Trifin',
    description: 'Tripole’s evolved form, confident and fast.',
    image: require('../assets/images/mons/trifin.png'),
    unlocked: false,
  },
  {
    id: 'orangeer',
    name: 'Orangeer',
    description: 'A friendly deer-like creature.',
    image: require('../assets/images/mons/orangeer.png'),
    unlocked: false,
  },
  {
    id: 'orangorn',
    name: 'Orangorn',
    description: 'Orangeer’s evolved form, tall and strong.',
    image: require('../assets/images/mons/orangorn.png'),
    unlocked: false,
  },
  {
    id: 'pinkhorn',
    name: 'Pinkhorn',
    description: 'A tiny pink blob.',
    image: require('../assets/images/mons/pinkhorn.png'),
    unlocked: false,
  },
  {
    id: 'pinkile',
    name: 'Pinkile',
    description: 'Pinkhorn’s evolved form, a bigger pink blob with arms and legs.',
    image: require('../assets/images/mons/pinkile.png'),
    unlocked: false,
  },
  {
    id: 'blople',
    name: 'Blople',
    description: 'A purple blob.',
    image: require('../assets/images/mons/blople.png'),
    unlocked: false,
  },
  {
    id: 'blopi',
    name: 'Blopi',
    description: 'Blople’s evolved form, with bigger horns.',
    image: require('../assets/images/mons/blopi.png'),
    unlocked: false,
  },
  {
    id: 'cloudie',
    name: 'Cloudie',
    description: 'A grey, fluffy cloud.',
    image: require('../assets/images/mons/cloudie.png'),
    unlocked: false,
  },
  {
    id: 'cloudiery',
    name: 'Cloudiery',
    description: 'Cloudie’s evolved form, a bigger, fluffier cloud.',
    image: require('../assets/images/mons/cloudiery.png'),
    unlocked: false,
  },
  {
    id: 'mikue',
    name: 'Mikue',
    description: 'A cheerful blue blob with music in its soul.',
    image: require('../assets/images/mons/mikue.png'),
    unlocked: false,
  },
  {
    id: 'mikui',
    name: 'Mikui',
    description: 'Mikue’s evolved form. It hums melodies that soothe minds.',
    image: require('../assets/images/mons/mikui.png'),
    unlocked: false,
  },
  {
    id: 'peinto',
    name: 'Peinto',
    description: 'A tiny fly with pointy wings.',
    image: require('../assets/images/mons/peinto.png'),
    unlocked: false,
  },
  {
    id: 'peinty',
    name: 'Peinty',
    description: 'Peinto’s evolved form, with even pointier wings.',
    image: require('../assets/images/mons/peinty.png'),
    unlocked: false,
  },
  {
    id: 'snailie',
    name: 'Snailie',
    description: 'A shy snail.',
    image: require('../assets/images/mons/snailie.png'),
    unlocked: false,
  },
  {
    id: 'snailfly',
    name: 'Snailfly',
    description: 'Snailie’s evolved form, still a shy snail.',
    image: require('../assets/images/mons/snailfly.png'),
    unlocked: false,
  },
  {
    id: 'starie',
    name: 'Starie',
    description: 'A bright, yellow star.',
    image: require('../assets/images/mons/starie.png'),
    unlocked: false,
  },
  {
    id: 'starkle',
    name: 'Starkle',
    description: 'Starie’s evolved form, its glow guides lost travelers at night.',
    image: require('../assets/images/mons/starkle.png'),
    unlocked: false,
  },
  {
    id: 'quadsun',
    name: 'Quadsun',
    description: 'A radiant sun pulsing with energy.',
    image: require('../assets/images/mons/quadsun.png'),
    unlocked: false,
  },
  {
    id: 'plenusun',
    name: 'Plenusun',
    description: 'Quadsun’s evolved form, its blazing presence lights entire valleys.',
    image: require('../assets/images/mons/plenusun.png'),
    unlocked: false,
  },
  {
    id: 'piscibes',
    name: 'Piscibes',
    description: 'A flying fish. Literally.',
    image: require('../assets/images/mons/piscibes.png'),
    unlocked: false,
  },
  {
    id: 'fisubis',
    name: 'Fisubis',
    description: 'Piscibes’s evolved form, glides through the air like a silent wave.',
    image: require('../assets/images/mons/fisubis.png'),
    unlocked: false,
  },
  {
    id: 'shroomie',
    name: 'Shroomie',
    description: 'A bouncy mushroom with a happy face.',
    image: require('../assets/images/mons/shroomie.png'),
    unlocked: false,
  },
  {
    id: 'shroomush',
    name: 'Shroomush',
    description: 'Shroomie’s evolved form, emits a calming spore cloud.',
    image: require('../assets/images/mons/shroomush.png'),
    unlocked: false,
  },
  {
    id: 'cattus',
    name: 'Cattus',
    description: 'A cat...?',
    image: require('../assets/images/mons/cattus.png'),
    unlocked: false,
  },
  {
    id: 'catspiravit',
    name: 'Catspiravit',
    description: 'Cattus’s evolved form, a spiritual cat.',
    image: require('../assets/images/mons/catspiravit.png'),
    unlocked: false,
  },
  {
    id: 'pavo',
    name: 'Pavo',
    description: 'Pretty like a peacock.',
    image: require('../assets/images/mons/pavo.png'),
    unlocked: false,
  },
  {
    id: 'pavilius',
    name: 'Pavilius',
    description: 'Pavo’s evolved form, a full-fledged bird.',
    image: require('../assets/images/mons/pavilius.png'),
    unlocked: false,
  },
  {
    id: 'axel',
    name: 'Axel',
    description: 'A pink, water mon.',
    image: require('../assets/images/mons/axel.png'),
    unlocked: false,
  },
  {
    id: 'axol',
    name: 'Axol',
    description: 'Axel’s evolved form, its fins glow with energy.',
    image: require('../assets/images/mons/axol.png'),
    unlocked: false,
  },
  {
    id: 'froggie',
    name: 'Froggie',
    description: 'A playful frog with sticky toes.',
    image: require('../assets/images/mons/froggie.png'),
    unlocked: false,
  },
  {
    id: 'frogroak',
    name: 'Frogroak',
    description: 'Froggie’s evolved form, its croak echoes through swamps.',
    image: require('../assets/images/mons/frogroak.png'),
    unlocked: false,
  },
  {
    id: 'dimidium',
    name: 'Dimidium',
    description: 'A split mon of dark and light halves.',
    image: require('../assets/images/mons/dimidium.png'),
    unlocked: false,
  },
  {
    id: 'dimidietas',
    name: 'Dimidietas',
    description: 'Dimidium’s evolved form, perfectly balanced in form and spirit.',
    image: require('../assets/images/mons/dimidietas.png'),
    unlocked: false,
  },
  {
    id: 'amoebus',
    name: 'Amoebus',
    description: ' A shape-shifting blob that never settles.',
    image: require('../assets/images/mons/amoebus.png'),
    unlocked: false,
  },
  {
    id: 'amoebi',
    name: 'Amoebi',
    description: 'Amoebus’s evolved form, it mimics forms with eerie precision.',
    image: require('../assets/images/mons/amoebi.png'),
    unlocked: false,
  },
  {
    id: 'clavicorn',
    name: 'Clavicorn',
    description: 'A striped, pointy mon.',
    image: require('../assets/images/mons/clavicorn.png'),
    unlocked: false,
  },
  {
    id: 'sid',
    name: 'Sid',
    description: 'Clavicorn’s evolved form, but upside down?',
    image: require('../assets/images/mons/sid.png'),
    unlocked: false,
  },
  {
    id: 'eu',
    name: 'Eu',
    description: 'It’s said to resemble a dessert.',
    image: require('../assets/images/mons/eu.png'),
    unlocked: false,
  },
  {
    id: 'ue',
    name: 'Ue',
    description: 'Eu’s evolved form, with extra toppings.',
    image: require('../assets/images/mons/ue.png'),
    unlocked: false,
  },
];

export default monList;